title: Lobby Lab
description: Un sitio personal con est√©tica del 2001

url: "https://jromano743.github.io"
baseurl: "/jromano743"

markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - post-templates
  - vendor
  - README.md
  - docker-compose.yml
  - .gitignore
  - update.sh
  - optimize-images.sh
