services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: myblog-jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --watch --force_polling --host 0.0.0.0
